#
# Application
#
jwt.privateKey=${JWT_PRIVATE_KEY:#{null}}
jwt.publicKey=${JWT_PUBLIC_KEY:#{null}}
#
# Spring
#
spring.application.name=${APP_NAME:@project.artifactId@}
spring.application.description=${APP_DESCR:prep auth service}
spring.application.version=${APP_VERSION:@project.version@}
server.port=${SERVER_PORT:8083}
app.cors.allowed-origins=*
#
# Database
#
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/${DB_NAME:prep}?currentSchema=prep_auth}
spring.datasource.username=${DB_USER:prep}
spring.datasource.password=${DB_PASS:prep}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.generate_statistics=false
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.check_nullability=true
spring.jpa.properties.hibernate.hbm2ddl.auto=validate
#
# Liquibase
#
spring.liquibase.enabled=true
spring.liquibase.liquibase-schema=public
spring.liquibase.database-change-log-table=prep_auth_log
spring.liquibase.database-change-log-lock-table=prep_auth_lock
spring.liquibase.change-log=classpath:db/changelog.yaml
#
# Logging
#
logging.level.root=${LOGGING_LEVEL_DEFAULT:INFO}
logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO
logging.level.org.postgresql=WARN
logging.level.org.apache.tomcat.util=WARN
